cookbook "ntp"
cookbook "git"
cookbook "chef-sbt"
cookbook "python"
cookbook "java"
cookbook "zookeeper"
cookbook "riak"
cookbook "rabbitmq"
cookbook "elasticsearch"
cookbook "logstash"
cookbook "kibana", git: 'git://github.com/lusis/chef-kibana.git'