#!/bin/sh

### BEGIN INIT INFO
# Provides:        titan
# Required-Start:  $network
# Required-Stop:   $network
# Default-Start:   2 3 4 5
# Default-Stop:    1
# Short-Description: Start Titan Graph Database
### END INIT INFO

PATH={{ titan_path }}/bin:$PATH

. /lib/lsb/init-functions


case $1 in
  start)
    titan.sh start
    ;;
  stop)
    titan.sh stop
    ;;
  restart)
    titan.sh stop
    titan.sh start
    ;;
  status)
    titan.sh status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
    ;;
esac